name: test_linux

on: [push, pull_request]

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, beta]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: robinraju/release-downloader@v1.4
        name: Download duckdb
        with:
          repository: "duckdb/duckdb"
          tag: "v1.3.2"
          fileName: libduckdb-linux-amd64.zip
          out-file-path: .
      - name: Linux extract duckdb
        if: matrix.os == 'ubuntu-latest'
        uses: ihiroky/extract-action@v1
        with:
          file_path: ${{ github.workspace }}/libduckdb-linux-amd64.zip
          extract_dir: libduckdb
          
      - name: Downloading test files
        run: wget -O process_mining/test_data/out.zip https://rwth-aachen.sciebo.de/s/4cvtTU3lLOgtxt1/download
      - name: Unpacking test files
        run: 7z x process_mining/test_data/out.zip -oprocess_mining/test_data
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib -p process_mining --all-features
        env:
          DUCKDB_LIB_DIR: ${{ github.workspace }}/libduckdb
          DUCKDB_INCLUDE_DIR: ${{ github.workspace }}/libduckdb
          LD_LIBRARY_PATH: ${{ github.workspace }}/libduckdb
